#Used to disable password ssh
- hosts: "*"
  become: yes
  tasks:
    - name: Transfer sshd config
      template: src=sshd_config dest=/etc/ssh dest=/etc/ssh/sshd_config

    - name: Restart sshd service to apply changes
      systemd:
        name: sshd
        state: restarted
        daemon_reload: true